[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rl_hockey"
version = "0.1.0"
description = "RL Hockey Project"

# This automatically finds the packages inside src/
[tool.setuptools.packages.find]
where = ["src"]